import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'fa';
export type Currency = 'USD' | 'IRR' | 'EUR';

interface LanguageContextType {
  language: Language;
  direction: 'ltr' | 'rtl';
  currency: Currency;
  setLanguage: (lang: Language) => void;
  setCurrency: (curr: Currency) => void;
  t: (key: string, defaultText?: string) => string;
  formatPrice: (amountInUsd: number) => string;
  formatDate: (dateString: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Brand
    brandName: 'FIRSTMIND',
    brandTagline: 'Production-Grade AI Creative SaaS Platform',

    // Nav
    navHome: 'Home',
    navFeatures: 'Features',
    navPricing: 'Pricing',
    navDashboard: 'Dashboard',
    navCreate: 'Create',
    navChat: 'Chat AI',
    navHistory: 'History',
    navBilling: 'Billing',
    navReferrals: 'Referrals',
    navNotifications: 'Notifications',
    navProfile: 'Settings',
    navAdmin: 'Admin Suite',
    navLogin: 'Sign In',
    navRegister: 'Get Started',
    navLogout: 'Sign Out',

    // Tools
    toolTextToImage: 'Text to Image',
    toolImageToImage: 'Image to Image',
    toolVariation: 'Variation Engine',
    toolEnhance: 'Enhance & Upscale',
    toolStyleTransfer: 'Style Transfer',
    toolTextToVideo: 'Text to Video',
    toolImageToVideo: 'Image to Video',

    // Statuses
    statusActive: 'Active',
    statusExpired: 'Expired',
    statusCancelled: 'Cancelled',
    statusPending: 'Pending',
    statusQueued: 'Queued',
    statusProcessing: 'Processing',
    statusCompleted: 'Completed',
    statusFailed: 'Failed',

    // Auth & Dev Test Mode
    signInTitle: 'Sign in to FIRSTMIND',
    signInDesc: 'Enter your credentials to access your creative studio and assets',
    devTestModeTitle: 'Development AI Test Mode',
    devTestModeDesc: 'Enables immediate testing of the Gemini Image & Chat providers without requiring a subscription. Generations are not billed.',
    devTestModeBtn: 'AI Test Mode — Development',
    devNoticeBanner: 'Development AI Mode — generation usage is not billed',
    devNoticeSub: 'Testing enabled for Gemini Image & Chat providers without requiring billing or active subscription.',
    emailLabel: 'Email Address',
    emailPlaceholder: 'creator@studio.com',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    signUpTitle: 'Create your FIRSTMIND Account',
    signUpDesc: 'Join professional creators utilizing precision AI generative engines',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'Alex Wright',
    confirmPasswordLabel: 'Confirm Password',
    referralCodeLabel: 'Referral Code (Optional)',
    agreeToTerms: 'By registering, you agree to our Terms of Service and Privacy Policy.',
    passwordsDoNotMatch: 'Passwords do not match.',
    passwordMinLength: 'Password must be at least 8 characters long.',
    fillAllFields: 'Please fill in all required fields.',
    signInError: 'Failed to sign in. Please verify your credentials.',
    registerError: 'Failed to register account.',

    // Studio & Image Tools
    studioTitleText: 'Text to Image Studio',
    studioTitleImage: 'Image to Image Engine',
    studioTitleVariation: 'Variation Studio',
    studioTitleEnhance: 'Super-Resolution & Upscaler',
    studioTitleStyle: 'Style & Lighting Transfer',
    studioSubtitle: 'Deterministic inference pipeline with real-time transactional credit accounting.',
    openChatAssistant: 'Open AI Chat Assistant',
    referenceImage: 'Reference Image (Required)',
    dropImageHere: 'Click or drag & drop reference image here',
    maxFileSize: 'PNG, JPG, WEBP up to 10MB',
    removeImage: 'Remove',
    transformationStrength: 'Transformation Strength',
    transformationStrengthDesc: 'Lower values stay closer to source geometry; higher values introduce extensive neural reinterpretation.',
    promptLabel: 'Creation Prompt',
    promptPlaceholder: 'Describe the scene, artistic style, lighting, and composition in detail...',
    promptCharCount: 'characters',
    samplePromptsTitle: 'Inspiration Presets',
    samplePrompt1: 'A high-contrast cinematic portrait of an astrophysicist bathed in holographic cyan and tungsten studio lighting, 85mm lens.',
    samplePrompt2: 'An architectural sanctuary villa perched on Nordic granite cliffs, minimalist cedar and glass, misty morning atmosphere.',
    samplePrompt3: 'Macro photograph of a mechanical chronometer movement with exposed rubies, brushed titanium gears, extreme depth of field.',
    samplePrompt4: 'A futuristic Persian-inspired city at night, cinematic lighting, highly detailed architecture, glowing cyan waterways.',
    negativePromptLabel: 'Negative Prompt (Avoid)',
    negativePromptPlaceholder: 'blurry, low quality, artifacts, distorted anatomy...',
    aspectRatio: 'Aspect Ratio',
    aspectRatio1_1: '1:1 Square (Feed & Profile)',
    aspectRatio3_4: '3:4 Portrait (Art & Poster)',
    aspectRatio4_3: '4:3 Landscape (Display)',
    aspectRatio9_16: '9:16 Vertical (Story & Reels)',
    aspectRatio16_9: '16:9 Widescreen (Cinematic & Banner)',
    resolution: 'Output Resolution',
    resStandard: 'Standard (1024px)',
    resHigh: 'High Definition (2048px)',
    resUltra: 'Ultra Detail (4096px)',
    stylePreset: 'Aesthetic Style',
    styleNone: 'Natural / Unstyled',
    stylePhotorealistic: 'Photorealistic 35mm',
    styleCinematic: 'Cinematic Movie Still',
    styleAnime: 'Modern Anime / Cel Shaded',
    styleDigitalArt: 'Concept Digital Art',
    style3DIso: '3D Isometric Render',
    styleMinimalist: 'Minimalist Vector & Graphic',
    styleWatercolor: 'Expressive Watercolor',
    generatingTitle: 'Synthesizing Neural Composition...',
    generatingSubtitle: 'Gemini inference pipeline is processing tokens and rendering visual diffusion matrix.',
    completedResult: 'Generated Composition',
    downloadImage: 'Download Asset',
    zoomImage: 'Fullscreen Zoom',
    copyPrompt: 'Copy Prompt',
    variationFromThis: 'Create Variation',
    retryGeneration: 'Regenerate',
    devTestActive: 'Dev Test Active',
    devFree: 'Dev Free',
    cost: 'Cost',
    balance: 'Balance',
    upgrade: 'Upgrade',
    keyboardShortcutHint: 'Press Ctrl+Enter or ⌘+Enter to generate',
    emptyResultTitle: 'Canvas Waiting for Synthesis',
    emptyResultDesc: 'Write your detailed prompt or pick an inspiration preset, configure your aspect ratio, and start the generation pipeline.',

    // FirstMind AI Chat Assistant
    chatTitle: 'FirstMind AI Creative Assistant',
    chatSubtitle: 'Brainstorm concepts, draft high-fidelity prompts, and refine visual styles with Gemini.',
    clearChat: 'Clear Chat',
    chatStarterCyberpunk: 'Help me formulate a cinematic cyberpunk street prompt with neon reflections',
    chatStarterPortrait: 'Suggest a high-fashion editorial portrait with natural soft window lighting',
    chatStarterMacro: 'Write a photorealistic macro shot prompt of dew drops on autumn leaves',
    chatStarterArch: 'Create a minimalist architectural villa prompt in Scandinavian style',
    chatInputPlaceholder: 'Ask FirstMind anything, or request help perfecting your image prompt (Press Enter to send)...',
    send: 'Send',
    createImageFromPrompt: 'Create image from this prompt',
    promptTransferred: 'Prompt transferred to Creative Studio',
    modelIndicator: 'Model',
    creativeAssistant: 'Assistant',
    you: 'You',

    // Dashboard & Overview
    welcomeBack: 'Welcome back',
    studioId: 'Studio ID',
    accessTier: 'Access Tier',
    unsubscribed: 'Unsubscribed',
    historyArchive: 'History Archive',
    quickCreationStudio: 'Quick Creation Engines',
    recentGenerationsTitle: 'Recent AI Generations',
    viewAllHistory: 'View Complete History',
    recentBilling: 'Recent Transactions',
    referralEarnings: 'Referral Commissions',
    earnPerSub: 'Earn $1.00 recurring for every qualifying creator you refer to FIRSTMIND.',

    // Sidebar
    navStudioHeading: 'AI Image Studio',
    navVideoHeading: 'AI Video Studio',
    navFinanceHeading: 'Finance & Account',
    subscriptionHeading: 'Subscription',
    noActivePlan: 'No Active Plan',
    selectPlan: 'Select Plan',
    credits: 'Credits',
    firstMindChat: 'FirstMind Chat',

    // History View
    filterAllTypes: 'All Media Types',
    filterImagesOnly: 'Images Only',
    filterVideosOnly: 'Videos Only',
    filterAllStatuses: 'All Statuses',
    filterCompleted: 'Completed',
    filterProcessing: 'Processing',
    filterFailed: 'Failed',
    prompt: 'Prompt',
    created: 'Created',
    actions: 'Actions',
    viewAsset: 'View Asset',
    deleteAsset: 'Delete',

    // Billing & Plans
    availablePlans: 'Available Subscription Tiers',
    paymentHistory: 'Payment Invoices',
    payWithIranianGateway: 'Iranian Shetab Gateway (Rial / Toman)',
    payWithCrypto: 'Cryptocurrency (USDT / BTC / ETH)',
    payWithStripe: 'International Credit Card (Stripe)',
    invoiceNumber: 'Invoice',
    amount: 'Amount',
    date: 'Date',
    status: 'Status',
    paymentMethod: 'Payment Method',

    // Profile & Settings
    accountDetails: 'Account Details',
    languagePreference: 'Language Preference',
    englishLang: 'English',
    persianLang: 'Persian (فارسی)',
    timezone: 'Timezone',
    securitySettings: 'Security & Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    saveChanges: 'Save Changes',
    passwordUpdated: 'Password updated successfully.',
    profileUpdated: 'Profile updated successfully.',

    // Referrals
    referralsDesc: 'Earn recurring commissions on every creator you invite to FIRSTMIND.',
    yourReferralLink: 'Your Unique Referral Link',
    totalEarned: 'Total Earnings',
    activeReferrals: 'Active Referrals',
    pendingPayout: 'Pending Payout',
    leaderboardTitle: 'Referral Leaderboard',
    monthlyLeaderboard: 'Monthly',
    allTimeLeaderboard: 'All Time',

    // Empty States
    emptyGenerationsTitle: 'No generations yet.',
    emptyGenerationsDesc: 'Create your first digital artwork or video sequence using our neural creative engines.',
    emptyPaymentsTitle: 'No payment history yet.',
    emptyPaymentsDesc: 'Your verified invoices, receipts, and subscription transactions will appear here.',
    emptyReferralsTitle: 'No referrals yet.',
    emptyReferralsDesc: 'Share your referral link to earn a $1.00 recurring commission on every qualifying subscriber.',
    emptyNotificationsTitle: 'You have no notifications.',
    emptyNotificationsDesc: 'Real-time updates regarding generation jobs and billing will be logged here.',
    emptyLeaderboardTitle: 'No referral leaderboard entries yet.',
    emptyLeaderboardDesc: 'Rankings will appear as verified referral commissions are completed.',

    // Common actions
    btnGenerate: 'Generate',
    btnProcessing: 'Synthesizing...',
    btnDownload: 'Download Asset',
    btnRetry: 'Retry Generation',
    btnCancel: 'Cancel',
    btnSave: 'Save Changes',
    btnSubscribe: 'Activate Subscription',
    btnUpgrade: 'Upgrade Plan',
    btnCopyLink: 'Copy Referral Link',
    copied: 'Copied to clipboard!',

    // Labels
    creditsRemaining: 'Remaining Credits',
    creditsCost: 'Credit Cost',
    currentPlan: 'Current Plan',

    // ==================== LANDING VIEW ====================
    landingBadge: 'Production AI Image & Video Studio',
    landingTitle: 'Precision AI Generation for Creative Professionals',
    landingDesc: 'FIRSTMIND provides an enterprise-grade web platform for text-to-image, image-to-image, and temporal video synthesis with deterministic usage ledgers and verified billing.',
    landingCtaAuth: 'Enter Studio Dashboard',
    landingCta: 'Start Creating Now',
    landingCtaSecondary: 'Inspect Plans & Pricing',
    trustDataIsolation: 'Strict Data Isolation',
    trustNoFakeData: 'No Fake Generation Data',
    trustVerifiedBilling: 'Verified Server Billing',

    // Gallery
    galleryTitle: 'What Our Users Create',
    galleryDesc: 'Explore the range of visual media produced by FIRSTMIND creators using advanced AI neural engines.',
    galleryImg1Title: 'Cyberpunk Metropolis',
    galleryImg1Desc: 'Neon-lit urban corridor with volumetric fog',
    galleryImg2Title: 'Ethereal Portrait',
    galleryImg2Desc: 'Fashion editorial with natural window lighting',
    galleryImg3Title: 'Botanical Macro',
    galleryImg3Desc: 'Dew drops on autumn leaves at golden hour',
    galleryCreatedBy: 'Created by',

    capabilitiesTitle: 'Engineered for High-Throughput Media Synthesis',
    capabilitiesDesc: 'Integrated neural tools designed with clean API abstractions and reliable state machines.',
    cap1Title: 'Text to Image Synthesis',
    cap1Desc: 'Generate high-fidelity raster digital artwork, editorial graphics, and conceptual photography using Gemini Flash Image.',
    cap2Title: 'Image to Image Evolution',
    cap2Desc: 'Upload reference images to guide structure, palette, and composition with granular strength and prompt guidance.',
    cap3Title: 'Variation & Style Transfer',
    cap3Desc: 'Explore compositional iterations or remap aesthetic styles and lighting across existing visual assets.',
    cap4Title: 'Neural Video Generation',
    cap4Desc: 'Synthesize coherent 6-15s temporal video sequences from text prompts or static reference imagery powered by Veo.',
    cap5Title: 'Real Usage Ledgers',
    cap5Desc: 'Transactional credit debiting with automatic refunds on failed jobs. Zero hidden costs or fake consumption.',
    cap6Title: 'Referral Partner Program',
    cap6Desc: 'Earn a verified $1.00 recurring commission into your referral ledger for every qualifying subscriber you introduce.',
    workflowTitle: 'Predictable Architectural Workflow',
    workflowDesc: 'From initial prompt configuration to verified download, every state transition is auditable.',
    step1Title: 'Sign Up & Verification',
    step1Desc: 'Create your account with secure PBKDF2 authentication, locale preferences, and optional referral code.',
    step2Title: 'Activate Creative Plan',
    step2Desc: 'Choose from Starter ($10), Pro ($50), or Elite ($99) tiers with verified multi-gateway payment checkout.',
    step3Title: 'Configure Neural Engine',
    step3Desc: 'Select image or video tools, configure aspect ratios (1:1, 16:9, 9:16), prompt guidance, and quality.',
    step4Title: 'Synthesize & Export',
    step4Desc: 'Track jobs through queued, processing, and completed states. Download lossless assets and view history.',
    pricingTitle: 'Simple, Transparent Pricing',
    pricingDesc: 'Fixed monthly quotas, zero surprise fees, and full credit rollover protection during billing cycles.',
    starterPlan: 'Starter',
    starterDesc: 'For creators starting their neural synthesis journey.',
    starterFeature1: '100 Monthly Generation Credits',
    starterFeature2: 'Text to Image & Image to Image',
    starterFeature3: 'Standard Queue Priority',
    starterFeature4: 'Commercial Usage Rights',
    getStarted: 'Get Started',
    proPlan: 'Pro Studio',
    proDesc: 'High-throughput creative suite for studios and designers.',
    proFeature1: '600 Monthly Generation Credits',
    proFeature2: 'All Image Tools + Veo Video Generation',
    proFeature3: 'High-Resolution up to 2K',
    proFeature4: 'High Queue Priority Execution',
    selectProPlan: 'Select Pro Plan',
    elitePlan: 'Elite Agency',
    eliteDesc: 'Uncapped concurrency and 4K ultra-resolution output.',
    eliteFeature1: '1,500 Monthly Generation Credits',
    eliteFeature2: 'Ultra-Fidelity 4K Synthesis',
    eliteFeature3: 'Top-Tier GPU Queue Execution',
    eliteFeature4: 'Dedicated Support & API Access',
    selectElitePlan: 'Select Elite Plan',
    referralBannerBadge: 'Partnership Program',
    referralBannerTitle: 'Earn $1.00 for every qualifying referred subscriber',
    referralBannerDesc: 'Every registered user receives a unique referral code and tracking URL. When your referred user activates any subscription plan, a verified $1 commission is atomically credited to your ledger.',
    viewReferralProgram: 'View Referral Program',
    perMonth: '/ month',

    // ==================== FEATURES VIEW ====================
    featuresBadge: 'Architecture & Capabilities',
    featuresTitle: 'Professional Neural Creative Suite',
    featuresDesc: 'Deep architectural integration with cutting-edge Gemini and Veo diffusion models for reliable creative output.',
    featureTextToImageName: 'Text to Image Studio',
    featureTextToImageTag: 'Primary Creative Tool',
    featureTextToImageCost: '1 Credit / image',
    featureTextToImageDesc: 'High-fidelity latent image synthesis utilizing Gemini Flash Image. Translates complex descriptive prompts into rich photographic and digital compositions.',
    featureTextToImageSpec1: 'Aspect ratios: 1:1 (Square), 16:9 (Landscape), 9:16 (Story/Reels), 4:3, 3:4',
    featureTextToImageSpec2: 'Negative prompt support to strictly prune unwanted artifacts',
    featureTextToImageSpec3: 'Deterministic seed control for iterative variation reproducibility',
    featureTextToImageSpec4: 'Style presets: Photorealistic, Cinematic, Anime, Digital Painting, 3D Render',
    featureImageToImageName: 'Image to Image Guidance',
    featureImageToImageTag: 'Composition Preserving',
    featureImageToImageCost: '2 Credits / image',
    featureImageToImageDesc: 'Synthesize new iterations while conditioning on an input reference image. Adjust transformation strength to control fidelity to the original geometry.',
    featureImageToImageSpec1: 'Drag & drop JPG/PNG reference image upload up to 10MB',
    featureImageToImageSpec2: 'Continuous strength slider (0.1 subtle restyle to 0.9 conceptual reimagining)',
    featureImageToImageSpec3: 'Prompt-directed structural repainting and contextual enhancement',
    featureImageToImageSpec4: 'Lossless output delivery',
    featureVariationName: 'Variation & Iteration Engine',
    featureVariationTag: 'Exploratory Workflow',
    featureVariationCost: '2 Credits / generation',
    featureVariationDesc: 'Rapidly explore alternate creative directions without drifting from core aesthetic themes and lighting.',
    featureVariationSpec1: 'Multi-sample parallel generation pipelines',
    featureVariationSpec2: 'Visual consistency preservation across generated character assets',
    featureVariationSpec3: 'Dynamic composition perturbation',
    featureEnhanceName: 'Super-Resolution & Upscaler',
    featureEnhanceTag: 'Editorial Quality',
    featureEnhanceCost: '2 Credits / upscale',
    featureEnhanceDesc: 'Upscale and reconstruct high-frequency texture details, micro-contrast, and facial sharpness for 2K/4K display and print.',
    featureEnhanceSpec1: 'High-fidelity edge preservation without painterly blur artifacts',
    featureEnhanceSpec2: 'Noise reduction and chromatic aberration correction',
    featureEnhanceSpec3: 'Export ready for print and editorial publishing',
    featureStyleName: 'Style & Lighting Transfer',
    featureStyleTag: 'Neural Aesthetics',
    featureStyleCost: '2 Credits / transfer',
    featureStyleDesc: 'Apply fine art palettes, volumetric lighting models, and specific textural aesthetics onto source images with neural feature remapping.',
    featureStyleSpec1: 'Palette preservation and color harmony stabilization',
    featureStyleSpec2: 'Cinematic anamorphic lighting transfer',
    featureStyleSpec3: 'Granular prompt styling blend',
    featureVideoName: 'Veo Temporal Video Synthesis',
    featureVideoTag: 'Next-Gen Motion',
    featureVideoCost: '10 Credits / video',
    featureVideoDesc: 'State-of-the-art temporal diffusion synthesis powered by Veo. Creates smooth camera movements, cinematic panning, and character motion.',
    featureVideoSpec1: 'Text-to-Video and Image-to-Video motion synthesis',
    featureVideoSpec2: '6s and 15s sequence durations with cinematic 24fps motion coherence',
    featureVideoSpec3: 'Aspect ratios for widescreen desktop (16:9) and mobile vertical video (9:16)',
    launchTool: 'Launch',

    // ==================== PRICING VIEW ====================
    pricingBadge: 'Transparent Tiering',
    pricingPageTitle: 'Flexible Subscription Plans',
    pricingPageDesc: 'Select the monthly generation quota that matches your studio throughput. Change or cancel anytime.',
    monthlyCredits: 'Monthly Credits',
    creditsUnit: 'Credits',
    featuresIncluded: 'Features included:',
    maxResolution: 'Max Resolution:',
    queuePriority: 'Queue Priority:',
    recommended: 'Recommended',
    selectPlanBtn: 'Select Plan',
    strictUsageAccounting: 'Strict Usage Accounting',
    strictUsageAccountingDesc: 'If any generation job fails due to provider interruption, your credits are refunded immediately to your balance.',
    highThroughputGpus: 'High-Throughput GPUs',
    highThroughputGpusDesc: 'Pro and Elite tiers are routed to dedicated high-priority workers for minimal queue latency.',
    commercialRights: 'Commercial Rights',
    commercialRightsDesc: 'All assets generated under active subscription plans belong to your account with unrestricted commercial usage.',

    // ==================== DASHBOARD VIEW ====================
    dashboardWelcome: 'Welcome back',
    dashboardStudioId: 'Studio ID',
    dashboardAccessTier: 'Access Tier',
    dashboardHistoryArchive: 'History Archive',
    dashboardNewGeneration: 'New Generation',
    dashboardAvailableCredits: 'Available Credits',
    dashboardManagePlan: 'Manage plan',
    dashboardSubscriptionStatus: 'Subscription Status',
    dashboardNoPlan: 'No Plan',
    dashboardRenewsOn: 'Renews on',
    dashboardUpgradeToGenerate: 'Upgrade to generate',
    dashboardCompletedAssets: 'Completed Assets',
    dashboardRecentInLog: 'recent in log',
    dashboardViewArchive: 'View archive gallery',
    dashboardReferralCommissions: 'Referral Commissions',
    dashboardEarned: 'earned',
    dashboardInspectLedger: 'Inspect ledger & referrals',
    dashboardCreativeTools: 'Creative Tool Suites',
    dashboardPickModel: 'Pick a model pipeline',
    dashboardTextToImageDesc: 'Describe any concept',
    dashboardImageToImageDesc: 'Reference guided',
    dashboardVariationDesc: 'Aesthetic branching',
    dashboardEnhanceDesc: '2K/4K micro-detail',
    dashboardStyleDesc: 'Harmonize palettes',
    dashboardVideoDesc: 'Cinematic temporal motion',
    dashboardCredits: 'credits',
    dashboardReferralShareTitle: 'Share your creative studio referral link',
    dashboardReferralShareDesc: 'Earn guaranteed $1 commission for every creative professional who subscribes using your referral link.',
    dashboardLinkCopied: 'Link Copied!',
    dashboardCopyReferralLink: 'Copy Referral Link',
    dashboardViewLeaderboard: 'View Leaderboard',
    dashboardRecentGenerations: 'Recent Generations',
    dashboardViewAll: 'View all',
    dashboardMediaJob: 'Media generation job',
    dashboardPaymentActivity: 'Payment & Billing Activity',
    dashboardBillingCenter: 'Billing center',
    dashboardExplorePlans: 'Explore Plans',
    dashboardDetails: 'Details',
    dashboardCost: 'Cost',
    dashboardBalance: 'Balance',
    dashboardOpenChat: 'Open AI Chat Assistant',

    // ==================== CREATE IMAGE VIEW ====================
    createDevModeNotice: 'Development AI Mode — generation usage is not billed',
    createDevModeSub: 'Testing enabled for Gemini Image & Chat providers without requiring billing or active subscription.',
    createStudioTitleText: 'Text to Image Studio',
    createStudioTitleImage: 'Image to Image Engine',
    createStudioTitleVariation: 'Variation Studio',
    createStudioTitleEnhance: 'Super-Resolution & Upscaler',
    createStudioTitleStyle: 'Style & Lighting Transfer',
    createStudioSubtitle: 'Deterministic inference pipeline with real-time transactional credit accounting.',
    createDevTestActive: 'Dev Test Active',
    createCostLabel: 'Cost',
    createBalanceLabel: 'Balance',
    createUpgrade: 'Upgrade',
    createPillTextToImage: 'Text to Image',
    createPillImageToImage: 'Image to Image',
    createPillVariation: 'Variation',
    createPillEnhance: 'Enhance / Upscale',
    createPillStyle: 'Style Transfer',
    createRefImageRequired: 'Reference Image (Required)',
    createRemoveImage: 'Remove image',
    createClickOrDrag: 'Click to select or drag & drop reference image',
    createFileFormats: 'PNG, JPG, or WebP up to 15MB',
    createSubtleVariation: 'Subtle variation (0.1)',
    createHighTransformation: 'High transformation (0.95)',
    createPromptDescription: 'Prompt Description',
    createChars: 'chars',
    createPromptPlaceholder: 'Describe subjects, lighting, artistic perspective, color mood, and depth of field in detail...',
    createInspirationPresets: 'Inspiration Presets:',
    createNegativePromptOptional: 'Negative Prompt (Optional)',
    createNegativePromptDesc: 'Elements to strictly exclude',
    createNegativePlaceholder: 'blurry, distorted anatomy, watermark, text, out of frame, low quality...',
    createGenerationParams: 'Generation Parameters',
    createAspectRatio: 'Aspect Ratio',
    createSquare: '1:1 (Square)',
    createLandscape: '16:9 (Landscape)',
    createStory: '9:16 (Story / Reel)',
    createEditorial: '4:3 (Editorial)',
    createPortrait: '3:4 (Portrait)',
    createTargetResolution: 'Target Resolution',
    createStandard: 'Standard (1024x1024)',
    createHigh2K: 'High 2K (Upscaled)',
    createUltra4K: 'Ultra 4K (Elite only)',
    createAestheticStyle: 'Aesthetic Style',
    createPhotorealistic: 'Photorealistic',
    createCinematic: 'Cinematic',
    createDigitalArt: 'Digital Art',
    createAnime: 'Anime',
    create3DIso: '3D Isometric',
    createMinimalistVector: 'Minimalist Vector',
    createSynthesizing: 'Synthesizing High-Fidelity Asset',
    createGeneratingVia: 'Generating latent diffusion tensors via Gemini Flash Image...',
    createOutputCanvas: 'Output Canvas',
    createInspectFullscreen: 'Inspect Fullscreen',
    createAspectLabel: 'Aspect Ratio:',
    createResolutionLabel: 'Resolution:',
    createFileSize: 'File Size:',
    createCanvasReady: 'Canvas Ready',
    createCanvasDesc: 'Configure your prompt and parameters on the left, then click Generate to preview and download here.',
    createHistory: 'History',
    createPreviewTitle: 'Generated Artwork Preview',
    createPromptLabel: 'Prompt:',
    createClose: 'Close',
    createDownload: 'Download',
    createGenerationFailed: 'Generation Failed',
    createCreditsRefunded: 'Rule 24: Any charged credits have been automatically refunded.',
    createGenerateMedia: 'Generate Media',
    createCredit: 'Credit',
    createCredits: 'Credits',
    createInvalidImageFile: 'Please upload a valid image file (PNG, JPG, WebP).',
    createImageTooLarge: 'Uploaded image size exceeds 15MB limit.',
    createPromptRequired: 'Please provide a prompt describing your desired visual creation.',
    createSourceImageRequired: 'Please upload a source reference image for this tool.',
    createInsufficientCredits: 'Insufficient credits. Please upgrade your plan or purchase additional quota.',

    // ==================== CHAT VIEW ====================
    chatHeaderTitle: 'FirstMind AI Assistant',
    chatHeaderDesc: 'Creative prompt director, aesthetic advisor & visual concept brainstormer',
    chatDevTestMode: 'Dev Test Mode',
    chatRegenerate: 'Regenerate',
    chatClear: 'Clear',
    chatImageStudio: 'Image Studio',
    chatEmptyTitle: 'Explore Creative Ideas & Formulate Prompts',
    chatEmptyDesc: 'Ask anything about lighting styles, lens parameters, composition framing, color palettes, or artistic genres for your next generation.',
    chatEnterToSend: 'Enter to send',
    chatSend: 'Send',
    chatCopied: 'Copied',
    chatCopy: 'Copy',
    chatCreateImageFromPrompt: 'Create image from this prompt',
    chatTransferPrompt: 'Transfer prompt to Image Studio',
    chatThinking: 'Thinking with',
    chatGenerationInterrupted: 'Generation Interrupted',
    chatDismiss: 'Dismiss',

    // ==================== FORGOT PASSWORD ====================
    forgotPasswordTitle: 'Reset Password',
    forgotPasswordDesc: 'Enter your email to receive recovery instructions',
    forgotPasswordSent: 'Recovery Instructions Sent',
    forgotPasswordSentDesc: 'If an account with',
    forgotPasswordSentDesc2: 'exists, a password reset authorization link has been dispatched to your inbox.',
    forgotPasswordReturn: 'Return to Sign In',
    forgotPasswordSendReset: 'Send Reset Link',
    forgotPasswordBack: 'Back to Sign In',

    // ==================== LEGAL VIEWS ====================
    aboutBadge: 'Platform Architecture',
    aboutTitle: 'About FIRSTMIND',
    aboutDesc: 'FIRSTMIND was designed as a production-grade creative software platform built around high-reliability generative models. Rather than operating as a prototype, our infrastructure enforces strict transactional usage balances, verified payment reconciliation, and granular tenant isolation.',
    aboutLedgerTitle: 'Deterministic Ledgers',
    aboutLedgerDesc: 'Credits are debited only when jobs begin processing and are automatically refunded if external model endpoints experience timeouts or failures.',
    aboutZeroLeakTitle: 'Zero Data Leaks',
    aboutZeroLeakDesc: 'User assets are strictly scoped to the authenticated creator\'s ID. Generation files cannot be accessed or enumerated by other accounts.',
    contactBadge: 'Support & Inquiries',
    contactTitle: 'Contact Support',
    contactDesc: 'Our engineering and billing team is available for platform assistance, API integrations, and enterprise agreements.',
    contactEnterpriseTitle: 'Enterprise & Billing Desk',
    contactEmail: 'support@firstmind.ai',
    contactResponseTime: 'Response Time SLA:',
    contactResponseTimeDesc: 'Standard support responds within 24 hours. Pro and Elite tier subscribers receive priority 4-hour ticket turnaround.',
    contactSystemStatus: 'System Status:',
    contactSystemStatusDesc: 'All Gemini and Veo video pipelines are monitored 24/7 with automated failover handling.',
    termsTitle: 'Terms of Service',
    termsUpdated: 'Last updated: September 2026',
    terms1Title: 'Acceptance of Terms:',
    terms1Desc: 'By accessing or using FIRSTMIND, you agree to be legally bound by these Terms of Service. If you do not agree, do not register or use the platform.',
    terms2Title: 'Account & Security:',
    terms2Desc: 'You are responsible for safeguarding your login credentials. FIRSTMIND employs salted PBKDF2 cryptography and server-side token validation.',
    terms3Title: 'Generation Usage & Credits:',
    terms3Desc: 'Subscriptions grant a monthly allocation of generation credits. Unused credits expire at the end of the monthly billing cycle unless stated otherwise. Commercial rights to generated assets belong entirely to the user under active paid subscriptions.',
    terms4Title: 'Prohibited Content:',
    terms4Desc: 'Users may not generate defamatory, harassing, or illegal imagery. Accounts violating content safety policies are subject to immediate suspension with audit recording.',
    privacyTitle: 'Privacy Policy',
    privacyUpdated: 'Last updated: September 2026',
    privacy1Title: 'Data Collection:',
    privacy1Desc: 'We collect email, account name, hashed passwords, transaction identifiers, generation prompts, and resulting media files solely for delivering your creative services.',
    privacy2Title: 'Asset Confidentiality:',
    privacy2Desc: 'Generated visual assets are stored securely on isolated server storage. They are never published publicly or shared with third parties without your explicit action.',
    privacy3Title: 'No Unsolicited Tracking:',
    privacy3Desc: 'We do not sell user data to advertising networks. Analytical telemetry is strictly utilized for platform latency and error diagnostics.',
    refundTitle: 'Refund & Dispute Policy',
    refundUpdated: 'Last updated: September 2026',
    refund1Title: 'Automated Credit Refunds:',
    refund1Desc: 'If an AI generation job terminates with a failed status due to model downtime, the system automatically refunds the exact credit cost back to your balance immediately.',
    refund2Title: 'Subscription Refunds:',
    refund2Desc: 'Refund requests for subscription fees are eligible within 7 calendar days of charge if less than 10% of monthly quota has been consumed. Contact support@firstmind.ai with your transaction reference number.',

    // ==================== FOOTER ====================
    footerProduct: 'Product',
    footerTextToImage: 'Text to Image',
    footerImageToImage: 'Image to Image',
    footerTextToVideo: 'Text to Video (Veo)',
    footerSubscriptionPlans: 'Subscription Plans',
    footerPlatform: 'Platform',
    footerFeaturesOverview: 'Features Overview',
    footerAboutArchitecture: 'About Architecture',
    footerContactSupport: 'Contact & Support',
    footerReferralProgram: 'Referral Partner Program ($1)',
    footerLegal: 'Legal',
    footerTermsOfService: 'Terms of Service',
    footerPrivacyPolicy: 'Privacy Policy',
    footerRefundPolicy: 'Refund & Dispute Policy',
    footerCopyright: 'All rights reserved.',
    footerDataIsolation: 'Strict Data Isolation & Transactional Ledgers',
    footerAiOnline: 'AI Neural Engines Online',

    // ==================== SIDEBAR ====================
    sidebarSubscription: 'Subscription',
    sidebarNoActivePlan: 'No Active Plan',
    sidebarSelectPlan: 'Select Plan',
    sidebarCredits: 'Credits',
    sidebarReferral: '$1/sale',

    // ==================== HISTORY VIEW ====================
    historyTitle: 'Generation History Archive',
    historyDesc: 'Private, tenant-isolated repository of all your creative synthesis jobs.',
    historyAllMedia: 'All Media Types',
    historyImagesOnly: 'Images Only',
    historyVideosOnly: 'Videos Only',
    historyAllStatuses: 'All Statuses',
    historyCompleted: 'Completed',
    historyProcessing: 'Processing',
    historyFailed: 'Failed',
    historyLoading: 'Loading historical creative assets...',
    historyEmptyTitle: 'No generations yet.',
    historyEmptyDesc: 'Create your first digital artwork or video sequence using our neural creative engines.',
    historyLaunchStudio: 'Launch Text to Image Studio',
    historyInspect: 'Inspect',
    historyGet: 'Get',
    historySynthesizedAsset: 'Synthesized asset',
    historyCost: 'Cost',
    historyRetry: 'Retry Job',
    historyDeleteAsset: 'Delete Asset',
    historyConfirmDelete: 'Are you sure you want to delete this asset from your archive?',
    historyRetryFailed: 'Failed to retry generation.',
    historyDeleteFailed: 'Failed to delete generation.',
    historyModalTitle: 'Generation Archive Detail',
    historyPrompt: 'Prompt:',
    historyNegative: 'Negative:',
    historyTool: 'Tool:',
    historyRatio: 'Ratio:',
    historyResolution: 'Resolution:',
    historyCreated: 'Created:',
    historyDelete: 'Delete',
    historyClose: 'Close',
    historyDownloadOriginal: 'Download Original',

    // ==================== BILLING VIEW ====================
    billingTitle: 'Billing & Subscription Management',
    billingDesc: 'Real-time usage quotas, multi-gateway checkout, and verified invoice accounting.',
    billingRefresh: 'Refresh Ledger',
    billingCurrentPlan: 'Current Plan',
    billingFreeTier: 'Free Tier',
    billingNoSubscription: 'No Active Subscription',
    billingRenewsOn: 'Current cycle renews on',
    billingSubscribePrompt: 'Subscribe to an active tier to begin synthesizing media.',
    billingCreditsRemaining: 'Credits Remaining:',
    billingUsed: 'used',
    billingAvailable: 'available',
    billingCancelAutoRenew: 'Cancel Subscription Auto-Renew',
    billingCancelConfirm: 'Are you sure you wish to cancel auto-renewal? You will retain access until the end of your billing cycle.',
    billingCancelFailed: 'Cancellation failed.',
    billingActivePlan: 'Active Plan',
    billingPerMonth: '/ month',
    billingMonthlyCredits: 'Monthly Credits',
    billingCurrentTier: 'Current Tier',
    billingSelectPlanCheckout: 'Select Plan & Checkout',
    billingPaymentTitle: 'Payment Transactions & Tax Invoices',
    billingTransactionId: 'Transaction ID',
    billingPlan: 'Plan',
    billingAmount: 'Amount',
    billingProvider: 'Provider',
    billingStatus: 'Status',
    billingDate: 'Date',
    billingInvoice: 'Invoice',
    billingPlanSubscription: 'Plan Subscription',
    billingViewInvoice: 'View Invoice',
    billingEmptyTitle: 'No payment history yet.',
    billingEmptyDesc: 'Your verified invoices, receipts, and subscription transactions will appear here.',
    billingCheckoutTitle: 'Activate',
    billingCheckoutDesc: 'Select your preferred payment gateway to initiate transaction',
    billingMonthlyAutoRenew: 'Monthly auto-renew',
    billingPaymentProvider: 'Payment Provider',
    billingProceedToPayment: 'Proceed to Payment Gateway',
    billingPaymentFailed: 'Payment initiation failed.',
    billingTransactionRef: 'Transaction Ref:',
    billingAmountDue: 'Amount Due:',
    billingGateway: 'Gateway:',
    billingSimulating: 'Simulating Secure Gateway Handshake',
    billingSimulatingDesc: 'In production, the user completes card entry or crypto transfer via the provider\'s PCI-compliant redirect screen.',
    billingCancel: 'Cancel',
    billingConfirmVerify: 'Confirm & Verify Payment',
    billingVerifyFailed: 'Payment verification failed.',
    billingPaymentSuccess: 'Payment Verified Successfully!',
    billingQuotaAvailable: 'quota of',
    billingCreditsNowAvailable: 'credits is now available in your studio.',
    billingStartCreating: 'Start Creating Assets',
    billingTaxInvoice: 'Tax Invoice & Receipt',
    billingFirstMind: 'FIRSTMIND SaaS Technologies',
    billingInvoiceNumber: 'Invoice #',
    billingPaid: 'PAID',
    billingBilledTo: 'Billed To:',
    billingIssueDate: 'Issue Date:',
    billingDescription: 'Description',
    billingStudioSubscription: 'Studio Subscription Tier',
    billingTotalPaid: 'Total Paid:',
    billingReceiptNote: 'Verified electronic receipt generated by FIRSTMIND Transactional Ledger.',
    billingPrintSave: 'Print / Save PDF',

    // ==================== REFERRALS VIEW ====================
    referralsTitle: 'Referral Partner Dashboard',
    referralsBadge: '$1.00 USD / Qualifying Sale',
    referralsRule: 'Strict Rule 28: Earn verified $1.00 recurring commissions credited to your ledger upon every qualifying referred subscription.',
    referralsYourLink: 'Your Unique Referral Link',
    referralsInviteTitle: 'Invite other creators & earn automatic commissions',
    referralsInviteDesc: 'When a creator registers with your link or code and activates any paid tier (Starter, Pro, Elite), $1.00 is immediately recorded to your ledger.',
    referralsLoadingLink: 'Loading link...',
    referralsCopied: 'Copied!',
    referralsCopyLink: 'Copy Link',
    referralsTotalEarnings: 'Total Approved Earnings',
    referralsLifetimeSales: 'Lifetime qualifying sales',
    referralsMonthlyEarnings: "This Month's Earnings",
    referralsCurrentMonth: 'Current calendar month',
    referralsSubscribed: 'Subscribed Referrals',
    referralsActiveCustomers: 'Active paid customers',
    referralsLeaderboardRank: 'Global Leaderboard Rank',
    referralsUnranked: 'Unranked',
    referralsBasedOnCommissions: 'Based on real referral commissions',
    referralsReferredAccounts: 'Referred Accounts',
    referralsRecords: 'records',
    referralsEmptyTitle: 'No referrals yet.',
    referralsEmptyDesc: 'Share your referral link to earn a $1.00 recurring commission on every qualifying subscriber.',
    referralsCopyAction: 'Copy Referral Link',
    referralsCreator: 'Creator',
    referralsStatus: 'Status',
    referralsCommission: 'Commission',
    referralsRegistered: 'Registered',
    referralsPaidCommissioned: 'Paid / Commissioned',
    referralsRegisteredNoPlan: 'Registered (No Plan)',
    referralsLeaderboard: 'Referral Leaderboard',
    referralsGlobal: 'Global',
    referralsMonthly: 'Monthly',
    referralsLeaderboardEmptyTitle: 'No referral leaderboard entries yet.',
    referralsLeaderboardEmptyDesc: 'Rankings will appear as verified referral commissions are completed.',
    referralsSales: 'sales',

    // ==================== PROFILE VIEW ====================
    profileTitle: 'Account Settings & Security',
    profileDesc: 'Manage your personal profile, credentials, and localization preferences.',
    profilePersonalInfo: 'Personal Information',
    profileUpdatedSuccess: 'Profile preferences updated successfully.',
    profileEmailLabel: 'Email Address',
    profileEmailNote: 'Account emails cannot be altered directly.',
    profileFullName: 'Full Name',
    profileTimezone: 'Timezone',
    profileLanguage: 'Preferred Language',
    profileSavePreferences: 'Save Preferences',
    profileSecurityPassword: 'Security & Password',
    profilePasswordSuccess: 'Password updated successfully.',
    profileCurrentPassword: 'Current Password',
    profileNewPassword: 'New Password (min 8 chars)',
    profileConfirmPassword: 'Confirm New Password',
    profileUpdatePassword: 'Update Password',
    profileSecurityTitle: 'Security Credentials & Isolation',
    profileAuthScheme: 'Authentication Scheme:',
    profileAuthValue: 'PBKDF2 SHA-512 (10,000 iter)',
    profileTenantIsolation: 'Tenant Isolation:',
    profileTenantValue: 'Strict Scoped UID Storage',
    profileAccountCreated: 'Account Created:',

    // ==================== NOTIFICATIONS VIEW ====================
    notificationsTitle: 'Notification Feed',
    notificationsNew: 'New',
    notificationsDesc: 'Real-time updates regarding generation jobs, referrals, and subscription activity.',
    notificationsMarkAllRead: 'Mark All as Read',
    notificationsLoading: 'Loading notifications...',
    notificationsEmptyTitle: 'You have no notifications.',
    notificationsEmptyDesc: 'Real-time updates regarding generation jobs and billing will be logged here.',
    notificationsMarkRead: 'Mark as read',
  },
  fa: {
    // Brand
    brandName: 'فرست‌مایند',
    brandTagline: 'پلتفرم سازمانی هوش مصنوعی خلاق برای تولید تصویر و ویدیو',

    // Nav
    navHome: 'خانه',
    navFeatures: 'قابلیت‌ها',
    navPricing: 'تعرفه‌ها',
    navDashboard: 'داشبورد',
    navCreate: 'تولید محتوا',
    navChat: 'چت هوش مصنوعی',
    navHistory: 'تاریخچه تولیدات',
    navBilling: 'مالی و اشتراک',
    navReferrals: 'سیستم معرف و درآمد',
    navNotifications: 'اعلان‌ها',
    navProfile: 'تنظیمات حساب',
    navAdmin: 'پنل مدیریت',
    navLogin: 'ورود',
    navRegister: 'ثبت نام',
    navLogout: 'خروج از حساب',

    // Tools
    toolTextToImage: 'متن به تصویر',
    toolImageToImage: 'تصویر به تصویر',
    toolVariation: 'موتور واریاسیون',
    toolEnhance: 'ارتقا و افزایش کیفیت',
    toolStyleTransfer: 'انتقال سبک هنری',
    toolTextToVideo: 'متن به ویدیو',
    toolImageToVideo: 'تصویر به ویدیو',

    // Statuses
    statusActive: 'فعال',
    statusExpired: 'منقضی شده',
    statusCancelled: 'لغو شده',
    statusPending: 'در انتظار پرداخت',
    statusQueued: 'در صف پردازش',
    statusProcessing: 'در حال پردازش',
    statusCompleted: 'تکمیل شده',
    statusFailed: 'ناموفق',

    // Auth & Dev Test Mode
    signInTitle: 'ورود به حساب فرست‌مایند',
    signInDesc: 'اطلاعات حساب کاربری خود را برای دسترسی به استودیو هوش مصنوعی وارد کنید',
    devTestModeTitle: 'حالت تست توسعه هوش مصنوعی',
    devTestModeDesc: 'آزمایش مستقیم و نامحدود مدل‌های تصویر و چت جمینای بدون نیاز به اشتراک یا پرداخت مالی. استفاده در این حالت رایگان است.',
    devTestModeBtn: 'ورود به حالت تست توسعه هوش مصنوعی',
    devNoticeBanner: 'حالت توسعه هوش مصنوعی — تولید تصویر و چت بدون هزینه است',
    devNoticeSub: 'آزمایش مستقیم مدل‌های تصویر و چت جمینای بدون نیاز به اشتراک یا اتصال درگاه پرداخت.',
    emailLabel: 'آدرس ایمیل',
    emailPlaceholder: 'creator@studio.com',
    passwordLabel: 'رمز عبور',
    passwordPlaceholder: '••••••••',
    rememberMe: 'مرا به خاطر بسپار',
    forgotPassword: 'رمز عبور را فراموش کرده‌اید؟',
    dontHaveAccount: 'هنوز حساب کاربری ندارید؟',
    alreadyHaveAccount: 'قبلاً ثبت‌نام کرده‌اید؟',
    signUpTitle: 'ایجاد حساب کاربری در فرست‌مایند',
    signUpDesc: 'به جمع طراحان و تولیدکنندگان حرفه‌ای با برترین موتورهای هوش مصنوعی بپیوندید',
    fullNameLabel: 'نام و نام خانوادگی',
    fullNamePlaceholder: 'علی احمدی',
    confirmPasswordLabel: 'تکرار رمز عبور',
    referralCodeLabel: 'کد معرف (اختیاری)',
    agreeToTerms: 'با ثبت‌نام، تمامی قوانین و شرایط استفاده و حریم خصوصی را می‌پذیرید.',
    passwordsDoNotMatch: 'رمز عبور و تکرار آن یکسان نیستند.',
    passwordMinLength: 'رمز عبور باید حداقل ۸ کاراکتر باشد.',
    fillAllFields: 'لطفاً تمامی فیلدهای الزامی را تکمیل کنید.',
    signInError: 'ورود ناموفق بود. لطفاً صحت ایمیل و رمز عبور را بررسی نمایید.',
    registerError: 'ثبت‌نام با خطا مواجه شد. لطفاً دوباره تلاش کنید.',

    // Studio & Image Tools
    studioTitleText: 'استودیو متن به تصویر',
    studioTitleImage: 'موتور تصویر به تصویر',
    studioTitleVariation: 'استودیو واریاسیون و تنوع',
    studioTitleEnhance: 'ارتقا و افزایش کیفیت تصویر',
    studioTitleStyle: 'انتقال سبک و نورپردازی',
    studioSubtitle: 'پایپ‌لاین دقیق و پایدار تولید تصویر با مدیریت لحظه‌ای فرآیند و پردازش ابری.',
    openChatAssistant: 'گفتگو با دستیار هوش مصنوعی',
    referenceImage: 'تصویر مرجع (الزامی)',
    dropImageHere: 'تصویر مرجع را به اینجا بکشید یا برای انتخاب کلیک کنید',
    maxFileSize: 'فرمت‌های PNG، JPG و WEBP تا سقف ۱۰ مگابایت',
    removeImage: 'حذف تصویر',
    transformationStrength: 'میزان تاثیر تصویر مرجع',
    transformationStrengthDesc: 'مقادیر کمتر وفاداری بیشتری به هندسه تصویر اولیه دارند؛ مقادیر بیشتر تغییرات خلاقانه و جسورانه‌تری ایجاد می‌کنند.',
    promptLabel: 'توصیف و پرامپت تصویر',
    promptPlaceholder: 'صحنه، سبک بصری، جزئیات سوژه، زاویه نورپردازی و ترکیب‌بندی را با دقت بنویسید...',
    promptCharCount: 'کاراکتر',
    samplePromptsTitle: 'نمونه پرامپت‌های الهام‌بخش',
    samplePrompt1: 'پرتره سینمایی با کنتراست فوق‌العاده از یک دانشمند در نورپردازی نئونی فیروزه‌ای و تنگستن، لنز ۸۵ میلی‌متری.',
    samplePrompt2: 'ویلای معماری مینیمال لوکس بر فراز صخره‌های گرانیتی نوردیک، با چوب سدر و شیشه در مه گرگ و میش صبحگاهی.',
    samplePrompt3: 'عکاسی ماکرو با فوکوس خیره‌کننده از چرخ‌دنده‌های ساعت مچی تیتانیومی با یاقوت‌های کبود و جزئیات میکروسکوپی.',
    samplePrompt4: 'کلان‌شهر باستانی-آینده‌نگرانه به سبک مینیاتور ایرانی در شب، گنبدهای فیروزه‌ای پرنور و کانال‌های آب درخشان.',
    negativePromptLabel: 'پرامپت منفی (موارد نامطلوب که حذف شوند)',
    negativePromptPlaceholder: 'تار، کیفیت نامناسب، دست و اندام دفرمه، نویز، اعوجاج...',
    aspectRatio: 'نسبت ابعاد تصویر',
    aspectRatio1_1: '۱:۱ مربع (پست اینستاگرام و آواتار)',
    aspectRatio3_4: '۳:۴ عمودی استاندارد (پوستر و پرتره)',
    aspectRatio4_3: '۴:۳ افقی سنتی (نمایشگر و مانیتور)',
    aspectRatio9_16: '۹:۱۶ عمودی کامل (استوری، ریلز، تیک‌تاک)',
    aspectRatio16_9: '۱۶:۹ عریض سینمایی (یوتیوب و بنر)',
    resolution: 'کیفیت خروجی',
    resStandard: 'استاندارد (۱۰۲۴ پیکسل)',
    resHigh: 'وضوح بالا ۲K (۲۰۴۸ پیکسل)',
    resUltra: 'وضوح فوق‌العاده ۴K (۴۰۹۶ پیکسل)',
    stylePreset: 'سبک بصری هنری',
    styleNone: 'طبیعی / بدون سبک خاص',
    stylePhotorealistic: 'عکاسی واقع‌گرایانه ۳۵ میلی‌متری',
    styleCinematic: 'پلان سینمایی و فیلم هالیوودی',
    styleAnime: 'انیمه ژاپنی مدرن (Cel Shaded)',
    styleDigitalArt: 'هنر مفهومی دیجیتال (Concept Art)',
    style3DIso: 'رندر سه‌بعدی ایزومتریک',
    styleMinimalist: 'وکتور و گرافیک مینیمال',
    styleWatercolor: 'نقاشی آبرنگ زنده و لطیف',
    generatingTitle: 'در حال تولید اثر هنری با هوش مصنوعی...',
    generatingSubtitle: 'موتور جمینای در حال پردازش توکن‌های متنی و انتشار ماتریس تصویر با بالاترین دقت است.',
    completedResult: 'اثر تولید شده نهایی',
    downloadImage: 'دانلود فایل اصلی',
    zoomImage: 'نمایش بزرگ و تمام‌صفحه',
    copyPrompt: 'کپی پرامپت',
    variationFromThis: 'تولید تصویر مشابه',
    retryGeneration: 'تولید مجدد',
    devTestActive: 'حالت تست فعال',
    devFree: 'تست رایگان',
    cost: 'هزینه',
    balance: 'موجودی',
    upgrade: 'ارتقای پلن',
    keyboardShortcutHint: 'کلیدهای Ctrl+Enter یا ⌘+Enter برای تولید سریع',
    emptyResultTitle: 'بوم در انتظار شروع پردازش',
    emptyResultDesc: 'پرامپت خود را بنویسید یا یکی از گزینه‌های آماده را برگزینید، نسبت ابعاد را تعیین کرده و دکمه تولید را بزنید.',

    // FirstMind AI Chat Assistant
    chatTitle: 'دستیار هوش مصنوعی خلاق فرست‌مایند',
    chatSubtitle: 'ایده‌پردازی سناریو، نگارش پرامپت‌های حرفه‌ای و اصلاح سبک‌های بصری با هوش مصنوعی قدرتمند جمینای.',
    clearChat: 'پاک کردن گفتگو',
    chatStarterCyberpunk: 'یک پرامپت سینمایی برای خیابان سایبرپانک بارانی با بازتاب نورهای نئونی بنویس',
    chatStarterPortrait: 'یک پرامپت پرتره عکاسی مد و فشن با نور طبیعی ملایم پنجره پیشنهاد بده',
    chatStarterMacro: 'پرامپت عکاسی ماکرو با وضوح بسیار بالا از قطرات شبنم روی برگ پاییزی بساز',
    chatStarterArch: 'یک پرامپت برای طراحی ویلای معماری مینیمال به سبک اسکاندیناوی ایجاد کن',
    chatInputPlaceholder: 'از فرست‌مایند سوال بپرسید یا برای ساخت پرامپت کمک بگیرید (Enter برای ارسال)...',
    send: 'ارسال پیام',
    createImageFromPrompt: 'ارسال پرامپت به استودیو تصویر',
    promptTransferred: 'پرامپت با موفقیت به استودیو تصویر منتقل شد',
    modelIndicator: 'مدل',
    creativeAssistant: 'دستیار فرست‌مایند',
    you: 'شما',

    // Dashboard & Overview
    welcomeBack: 'خوش آمدید',
    studioId: 'شناسه استودیو',
    accessTier: 'سطح اشتراک',
    unsubscribed: 'بدون اشتراک فعال',
    historyArchive: 'آرشیو تاریخچه',
    quickCreationStudio: 'دسترسی سریع به ابزارهای تولید',
    recentGenerationsTitle: 'آخرین تولیدات با هوش مصنوعی',
    viewAllHistory: 'مشاهده کامل تاریخچه',
    recentBilling: 'تراکنش‌های اخیر',
    referralEarnings: 'درآمد کسب‌شده از معرفی',
    earnPerSub: 'به ازای هر کاربری که با لینک شما عضو و خریدار شود، ۱ دلار پاداش مستمر دریافت کنید.',

    // Sidebar
    navStudioHeading: 'استودیو تصویر هوش مصنوعی',
    navVideoHeading: 'استودیو ویدیو هوش مصنوعی',
    navFinanceHeading: 'حساب و بخش مالی',
    subscriptionHeading: 'وضعیت اشتراک',
    noActivePlan: 'بدون اشتراک فعال',
    selectPlan: 'انتخاب و خرید پلن',
    credits: 'اعتبار',
    firstMindChat: 'چت هوش مصنوعی',

    // History View
    filterAllTypes: 'تمام فرمت‌های رسانه',
    filterImagesOnly: 'فقط تصاویر',
    filterVideosOnly: 'فقط ویدیوها',
    filterAllStatuses: 'همه وضعیت‌ها',
    filterCompleted: 'تکمیل شده',
    filterProcessing: 'در حال پردازش',
    filterFailed: 'ناموفق',
    prompt: 'پرامپت',
    created: 'تاریخ ایجاد',
    actions: 'عملیات',
    viewAsset: 'مشاهده اثر',
    deleteAsset: 'حذف',

    // Billing & Plans
    availablePlans: 'پلن‌های عضویت در دسترس',
    paymentHistory: 'فاکتورها و سوابق پرداختی',
    payWithIranianGateway: 'درگاه پرداخت شتاب (ریال و تومان)',
    payWithCrypto: 'پرداخت امن رمزارز (تتر / بیت‌کوین / اتریوم)',
    payWithStripe: 'کارت‌های اعتباری بین‌المللی (مسترکارت و ویزا)',
    invoiceNumber: 'شماره فاکتور',
    amount: 'مبلغ',
    date: 'تاریخ',
    status: 'وضعیت',
    paymentMethod: 'روش پرداخت',

    // Profile & Settings
    accountDetails: 'مشخصات حساب کاربری',
    languagePreference: 'زبان پلتفرم',
    englishLang: 'English (انگلیسی)',
    persianLang: 'فارسی (Persian)',
    timezone: 'منطقه زمانی',
    securitySettings: 'امنیت و تغییر رمز عبور',
    currentPassword: 'رمز عبور فعلی',
    newPassword: 'رمز عبور جدید',
    saveChanges: 'ذخیره تغییرات',
    passwordUpdated: 'رمز عبور با موفقیت به‌روزرسانی شد.',
    profileUpdated: 'اطلاعات کاربری با موفقیت ذخیره شد.',

    // Referrals
    referralsDesc: 'با معرفی فرست‌مایند به دوستان و همکاران طراح خود، کمیسیون مستمر دریافت کنید.',
    yourReferralLink: 'لینک اختصاصی معرف شما',
    totalEarned: 'کل درآمد حاصله',
    activeReferrals: 'معرفی‌های موفق',
    pendingPayout: 'در انتظار واریز',
    leaderboardTitle: 'جدول برترین معرف‌ها',
    monthlyLeaderboard: 'ماهانه',
    allTimeLeaderboard: 'کل ادوار',

    // Empty States
    emptyGenerationsTitle: 'هنوز هیچ تصویری تولید نشده است.',
    emptyGenerationsDesc: 'اولین اثر هنری دیجیتال یا کلیپ ویدیویی خود را با موتورهای هوش مصنوعی ما خلق کنید.',
    emptyPaymentsTitle: 'هنوز سابقه پرداختی ثبت نشده است.',
    emptyPaymentsDesc: 'صورت‌حساب‌ها، رسیدها و تراکنش‌های اشتراک تایید شده شما در این بخش نمایش داده می‌شوند.',
    emptyReferralsTitle: 'هنوز هیچ کاربری با لینک شما ثبت‌نام نکرده است.',
    emptyReferralsDesc: 'لینک اختصاصی خود را به اشتراک بگذارید و به ازای هر خرید واجد شرایط ۱ دلار پاداش نقدی دریافت کنید.',
    emptyNotificationsTitle: 'هیچ اعلانی وجود ندارد.',
    emptyNotificationsDesc: 'گزارش رویدادهای تولید محتوا و پرداخت‌ها در اینجا ثبت خواهد شد.',
    emptyLeaderboardTitle: 'هنوز رتبه‌بندی فعالی ثبت نشده است.',
    emptyLeaderboardDesc: 'جدول برترین معرف‌ها پس از ثبت اولین کمیسیون‌های واقعی تشکیل می‌شود.',

    // Common actions
    btnGenerate: 'شروع تولید',
    btnProcessing: 'در حال پردازش و خلق...',
    btnDownload: 'دانلود فایل با کیفیت اصلی',
    btnRetry: 'تلاش مجدد',
    btnCancel: 'انصراف',
    btnSave: 'ذخیره تغییرات',
    btnSubscribe: 'فعال‌سازی اشتراک',
    btnUpgrade: 'ارتقای پلن',
    btnCopyLink: 'کپی لینک معرف',
    copied: 'در حافظه کپی شد!',

    // Labels
    creditsRemaining: 'اعتبار باقی‌مانده',
    creditsCost: 'هزینه اعتبار',
    currentPlan: 'پلن فعلی',

    // ==================== LANDING VIEW ====================
    landingBadge: 'استودیوی حرفه‌ای تولید تصویر و ویدیو با هوش مصنوعی',
    landingTitle: 'تولید دقیق و حرفه‌ای تصویر با هوش مصنوعی برای طراحان خلاق',
    landingDesc: 'فرست‌مایند یک پلتفرم وب سازمانی برای تبدیل متن به تصویر، تصویر به تصویر و ترکیب تصاویر متحرک با دفتر کل مالی شفاف و صورت‌حساب‌های تایید شده است.',
    landingCtaAuth: 'ورود به پنل داشبورد',
    landingCta: 'شروع خلق تصاویر',
    landingCtaSecondary: 'مشاهده تعرفه‌ها و پلن‌ها',
    trustDataIsolation: 'جداسازی کامل داده‌ها',
    trustNoFakeData: 'بدون داده‌های جعلی',
    trustVerifiedBilling: 'صورت‌حساب تایید شده',

    // گالری
    galleryTitle: 'آنچه کاربران ما خلق می‌کنند',
    galleryDesc: 'طیف رسانه‌های بصری تولید شده توسط خالقین FIRSTMIND با موتورهای هوش مصنوعی پیشرفته را کشف کنید.',
    galleryImg1Title: 'متروپولیس سایبرپانک',
    galleryImg1Desc: 'کوریدور شهری نئونی با مه حجمی',
    galleryImg2Title: 'پرتره اثیری',
    galleryImg2Desc: 'ادیتوریال مد با نور طبیعی پنجره',
    galleryImg3Title: 'ماکرو گیاه‌شناسی',
    galleryImg3Desc: 'قطرات شبنم روی برگ‌های پاییزی در ساعت طلایی',
    galleryCreatedBy: 'ساخته شده توسط',

    capabilitiesTitle: 'طراحی شده برای تولید رسانه با کیفیت و سرعت بالا',
    capabilitiesDesc: 'ابزارهای هوش مصنوعی یکپارچه با API ساده و ماشین‌های状态 قابل اعتماد.',
    cap1Title: 'تولید تصویر از متن',
    cap1Desc: 'تولید تصاویر دیجیتال با کیفیت بالا، گرافیک‌های تبلیغاتی و عکاسی مفهومی با مدل جمینای فلش.',
    cap2Title: 'تبدیل تصویر به تصویر',
    cap2Desc: 'آپلود تصاویر مرجع برای هدایت ساختار، پالت رنگی و ترکیب‌بندی با کنترل دقیق.',
    cap3Title: 'واریاسیون و انتقال سبک',
    cap3Desc: 'کشف ترکیب‌بندی‌های جدید یا بازآفرینی سبک‌های بصری و نورپردازی روی تصاویر موجود.',
    cap4Title: 'تولید ویدیو با هوش مصنوعی',
    cap4Desc: 'تولید ویدیوهای ۶ تا ۱۵ ثانیه‌ای هماهنگ از متن یا تصاویر ثابت با مدل ویو.',
    cap5Title: 'دفتر کل واقعی',
    cap5Desc: 'کسر اعتبار دقیق و بازپرداخت خودکار در صورت خطا. بدون هزینه‌های پنهان.',
    cap6Title: 'برنامه همکاری و معرف',
    cap6Desc: 'کسب درآمد ۱ دلاری مستمر برای هر کاربری که از طریق لینک شما عضو شود.',
    workflowTitle: 'فرآیند معماری قابل پیش‌بینی',
    workflowDesc: 'از پیکربندی اولیه پرامپت تا دانلود تایید شده، هر مرحله قابل ردیابی است.',
    step1Title: 'ثبت‌نام و تایید هویت',
    step1Desc: 'ایجاد حساب با امنیت PBKDF2، تنظیمات زبان و کد معرف اختیاری.',
    step2Title: 'فعال‌سازی پلن خلاقیت',
    step2Desc: 'انتخاب از پلن‌های استارتر (۱۰ دلار)، پرو (۵۰ دلار) یا الیت (۹۹ دلار) با درگاه‌های پرداخت متعدد.',
    step3Title: 'پیکربندی موتور هوش مصنوعی',
    step3Desc: 'انتخاب ابزارهای تصویر یا ویدیو، تنظیم نسبت ابعاد، کیفیت و راهنمای پرامپت.',
    step4Title: 'تولید و خروجی',
    step4Desc: 'ردیابی مراحل کار از صف تا تکمیل. دانلود فایل‌های بدون افت کیفیت.',
    pricingTitle: 'تعرفه ساده و شفاف',
    pricingDesc: 'سهمیه ماهانه ثابت، بدون هزینه‌های اضافی و محافظت کامل اعتبار در دوره صورت‌حساب.',
    starterPlan: 'استارتر',
    starterDesc: 'برای شروع سفر تولید تصویر با هوش مصنوعی.',
    starterFeature1: '۱۰۰ اعتبار تولید ماهانه',
    starterFeature2: 'متن به تصویر و تصویر به تصویر',
    starterFeature3: 'اولویت صف استاندارد',
    starterFeature4: 'حقوق استفاده تجاری',
    getStarted: 'شروع کنید',
    proPlan: 'پرو استودیو',
    proDesc: 'مجموعه خلاقیت پرسرعت برای استودیوها و طراحان.',
    proFeature1: '۶۰۰ اعتبار تولید ماهانه',
    proFeature2: 'تمام ابزارهای تصویری + تولید ویدیو ویو',
    proFeature3: 'کیفیت بالا تا ۲K',
    proFeature4: 'اولویت بالای صف پردازش',
    selectProPlan: 'انتخاب پلن پرو',
    elitePlan: 'الیت آژانس',
    eliteDesc: 'حداکثر همزمانی و کیفیت فوق‌العاده ۴K.',
    eliteFeature1: '۱,۵۰۰ اعتبار تولید ماهانه',
    eliteFeature2: 'تولید ۴K با کیفیت فوق‌العاده',
    eliteFeature3: 'اولویت بالای صف GPU',
    eliteFeature4: 'پشتیبانی اختصاصی و API',
    selectElitePlan: 'انتخاب پلن الیت',
    referralBannerBadge: 'برنامه همکاری',
    referralBannerTitle: '۱ دلار برای هر کاربر معرفی شده واجد شرایط',
    referralBannerDesc: 'هر کاربر ثبت‌نام شده یک کد معرف و لینک ردیابی اختصاصی دریافت می‌کند. وقتی کاربر معرفی شده شما هر پلن اشتراکی را فعال کند، ۱ دلار کمیسیون تایید شده به حساب شما واریز می‌شود.',
    viewReferralProgram: 'مشاهده برنامه معرف',
    perMonth: '/ ماه',

    // ==================== FEATURES VIEW ====================
    featuresBadge: 'معماری و قابلیت‌ها',
    featuresTitle: 'مجموعه حرفه‌ای خلاقیت هوش مصنوعی',
    featuresDesc: 'یکپارچگی عمیق با مدل‌های پیشرفته جمینای و ویو برای خروجی قابل اعتماد.',
    featureTextToImageName: 'استودیو متن به تصویر',
    featureTextToImageTag: 'ابزار اصلی خلاقیت',
    featureTextToImageCost: '۱ اعتبار / تصویر',
    featureTextToImageDesc: 'تولید تصویر با کیفیت بالا از متن با مدل جمینای فلش. تبدیل پرامپت‌های پیچیده به ترکیب‌های عکاسی و دیجیتال غنی.',
    featureTextToImageSpec1: 'نسبت ابعاد: ۱:۱ (مربع)، ۱۶:۹ (افقی)، ۹:۱۶ (استوری/ریلز)، ۴:۳، ۳:۴',
    featureTextToImageSpec2: 'پشتیبانی از پرامپت منفی برای حذف عناصر نامطلوب',
    featureTextToImageSpec3: 'کنترل دقیق سید برای تولید تکرارپذیر',
    featureTextToImageSpec4: 'پیش‌فرض‌های سبک: واقع‌گرایانه، سینمایی، انیمه، نقاشی دیجیتال، رندر ۳بعدی',
    featureImageToImageName: 'راهنمای تصویر به تصویر',
    featureImageToImageTag: 'حفظ ترکیب‌بندی',
    featureImageToImageCost: '۲ اعتبار / تصویر',
    featureImageToImageDesc: 'تولید ترکیب‌بندی‌های جدید با استفاده از تصویر مرجع. تنظیم میزان تغییر برای کنترل وفاداری.',
    featureImageToImageSpec1: 'آپلود تصویر مرجع JPG/PNG با کشیدن و رها کردن (تا ۱۰MB)',
    featureImageToImageSpec2: 'اسلایدر میزان تغییر (۰.۱ تغییر ظریف تا ۰.۹ بازآفرینی مفهومی)',
    featureImageToImageSpec3: 'رنگ‌آمیزی ساختاری هدایت‌شده با پرامپت',
    featureImageToImageSpec4: 'خروجی بدون افت کیفیت',
    featureVariationName: 'موتور واریاسیون و تکرار',
    featureVariationTag: 'فرآیند اکتشافی',
    featureVariationCost: '۲ اعتبار / تولید',
    featureVariationDesc: 'کشف سریع جهات خلاقیت جدید بدون انحراف از سبک و نورپردازی اصلی.',
    featureVariationSpec1: 'پایپ‌لاین‌های تولید موازی چند نمونه‌ای',
    featureVariationSpec2: 'حفظ یکپارچگی بصری در دارایی‌های شخصیت تولید شده',
    featureVariationSpec3: 'تغییر پویای ترکیب‌بندی',
    featureEnhanceName: 'افزایش کیفیت و بزرگ‌نمایی',
    featureEnhanceTag: 'کیفیت تحریریه',
    featureEnhanceCost: '۲ اعتبار / بزرگ‌نمایی',
    featureEnhanceDesc: 'بزرگ‌نمایی و بازسازی جزئیات بافت، کنتراست میکرو و وضوح برای نمایش و چاپ ۲K/۴K.',
    featureEnhanceSpec1: 'حفظ لبه‌ها با کیفیت بالا بدون تاری نقاشی',
    featureEnhanceSpec2: 'کاهش نویز و اصلاح اعوجاج رنگی',
    featureEnhanceSpec3: 'خروجی آماده چاپ و انتشار',
    featureStyleName: 'انتقال سبک و نورپردازی',
    featureStyleTag: 'زیبایی‌شناسی عصبی',
    featureStyleCost: '۲ اعتبار / انتقال',
    featureStyleDesc: 'اعمال پالت‌های هنری، مدل‌های نورپردازی حجمی و زیبایی‌شناسی خاص روی تصاویر با بازآفرینی ویژگی‌های عصبی.',
    featureStyleSpec1: 'حفظ پالت و ثبات هماهنگی رنگی',
    featureStyleSpec2: 'انتقال نورپردازی آنامورفیک سینمایی',
    featureStyleSpec3: 'ترکیب ظریف پرامپت و سبک',
    featureVideoName: 'تولید ویدیوی زمانی ویو',
    featureVideoTag: 'حرکت نسل جدید',
    featureVideoCost: '۱۰ اعتبار / ویدیو',
    featureVideoDesc: 'تولید پیشرفته ویدیو با انتشار زمانی توسط مدل ویو. ایجاد حرکات صاف دوربین، پنینگ سینمایی و حرکت شخصیت.',
    featureVideoSpec1: 'تولید حرکت متن به ویدیو و تصویر به ویدیو',
    featureVideoSpec2: 'مدت ۶ و ۱۵ ثانیه با هماهنگی حرکتی ۲۴ فریم در ثانیه',
    featureVideoSpec3: 'نسبت ابعاد برای دسکتاپ عریض (۱۶:۹) و ویدیوی عمودی موبایل (۹:۱۶)',
    launchTool: 'راه‌اندازی',

    // ==================== PRICING VIEW ====================
    pricingBadge: 'تعرفه‌گذاری شفاف',
    pricingPageTitle: 'پلن‌های اشتراک انعطاف‌پذیر',
    pricingPageDesc: 'سهمیه ماهانه تولید متناسب با نیاز خود را انتخاب کنید. تغییر یا لغو در هر زمان.',
    monthlyCredits: 'اعتبار ماهانه',
    creditsUnit: 'اعتبار',
    featuresIncluded: 'ویژگی‌های شامل:',
    maxResolution: 'حداکثر کیفیت:',
    queuePriority: 'اولویت صف:',
    recommended: 'پیشنهادی',
    selectPlanBtn: 'انتخاب پلن',
    strictUsageAccounting: 'حسابداری دقیق مصرف',
    strictUsageAccountingDesc: 'اگر هر کار تولیدی به دلیل قطعی ارائه‌دهنده ناموفق شود، اعتبار شما فوراً بازپرداخت می‌شود.',
    highThroughputGpus: 'پردازنده‌های گرافیکی پرسرعت',
    highThroughputGpusDesc: 'پلن‌های پرو و الیت به صف‌های اولویت بالا اختصاص داده می‌شوند.',
    commercialRights: 'حقوق تجاری',
    commercialRightsDesc: 'تمام دارایی‌های تولید شده در پلن‌های اشتراکی فعال متعلق به حساب شما هستند.',

    // ==================== DASHBOARD VIEW ====================
    dashboardWelcome: 'خوش آمدید',
    dashboardStudioId: 'شناسه استودیو',
    dashboardAccessTier: 'سطح دسترسی',
    dashboardHistoryArchive: 'آرشیو تاریخچه',
    dashboardNewGeneration: 'تولید جدید',
    dashboardAvailableCredits: 'اعتبار موجود',
    dashboardManagePlan: 'مدیریت پلن',
    dashboardSubscriptionStatus: 'وضعیت اشتراک',
    dashboardNoPlan: 'بدون پلن',
    dashboardRenewsOn: 'تمدید در',
    dashboardUpgradeToGenerate: 'ارتقا برای تولید',
    dashboardCompletedAssets: 'آثار تکمیل شده',
    dashboardRecentInLog: 'اخیراً در تاریخچه',
    dashboardViewArchive: 'مشاهده آرشیو',
    dashboardReferralCommissions: 'کمیسیون معرفی',
    dashboardEarned: 'کسب شده',
    dashboardInspectLedger: 'مشاهده دفتر کل و معرفی‌ها',
    dashboardCreativeTools: 'ابزارهای خلاقیت',
    dashboardPickModel: 'یک مدل انتخاب کنید',
    dashboardTextToImageDesc: 'توصیف هر مفهومی',
    dashboardImageToImageDesc: 'هدایت با تصویر مرجع',
    dashboardVariationDesc: 'شاخه‌های زیبایی‌شناختی',
    dashboardEnhanceDesc: 'جزئیات ۲K/۴K',
    dashboardStyleDesc: 'هماهنگی پالت‌ها',
    dashboardVideoDesc: 'حرکت سینمایی زمانی',
    dashboardCredits: 'اعتبار',
    dashboardReferralShareTitle: 'لینک معرفی استودیوی خلاقیت خود را به اشتراک بگذارید',
    dashboardReferralShareDesc: 'برای هر حرفه‌ای خلاقی که با لینک شما اشتراک فعال کند، ۱ دلار کمیسیون تضمینی دریافت کنید.',
    dashboardLinkCopied: 'لینک کپی شد!',
    dashboardCopyReferralLink: 'کپی لینک معرفی',
    dashboardViewLeaderboard: 'مشاهده رتبه‌بندی',
    dashboardRecentGenerations: 'آخرین تولیدات',
    dashboardViewAll: 'مشاهده همه',
    dashboardMediaJob: 'کار تولید رسانه',
    dashboardPaymentActivity: 'فعالیت مالی و صورت‌حساب',
    dashboardBillingCenter: 'مرکز مالی',
    dashboardExplorePlans: 'مشاهده پلن‌ها',
    dashboardDetails: 'جزئیات',
    dashboardCost: 'هزینه',
    dashboardBalance: 'موجودی',
    dashboardOpenChat: 'گفتگو با دستیار هوش مصنوعی',

    // ==================== CREATE IMAGE VIEW ====================
    createDevModeNotice: 'حالت توسعه هوش مصنوعی — تولید بدون هزینه است',
    createDevModeSub: 'آزمایش مستقیم مدل‌های تصویر و چت جمینای بدون نیاز به اشتراک.',
    createStudioTitleText: 'استودیو متن به تصویر',
    createStudioTitleImage: 'موتور تصویر به تصویر',
    createStudioTitleVariation: 'استودیو واریاسیون',
    createStudioTitleEnhance: 'افزایش کیفیت و بزرگ‌نمایی',
    createStudioTitleStyle: 'انتقال سبک و نورپردازی',
    createStudioSubtitle: 'پایپ‌لاین دقیق تولید تصویر با مدیریت لحظه‌ای فرآیند.',
    createDevTestActive: 'حالت تست فعال',
    createCostLabel: 'هزینه',
    createBalanceLabel: 'موجودی',
    createUpgrade: 'ارتقا',
    createPillTextToImage: 'متن به تصویر',
    createPillImageToImage: 'تصویر به تصویر',
    createPillVariation: 'واریاسیون',
    createPillEnhance: 'افزایش کیفیت',
    createPillStyle: 'انتقال سبک',
    createRefImageRequired: 'تصویر مرجع (الزامی)',
    createRemoveImage: 'حذف تصویر',
    createClickOrDrag: 'برای انتخاب کلیک کنید یا تصویر را بکشید و رها کنید',
    createFileFormats: 'PNG، JPG یا WebP تا ۱۵MB',
    createSubtleVariation: 'تغییر ظریف (۰.۱)',
    createHighTransformation: 'تغییر زیاد (۰.۹۵)',
    createPromptDescription: 'توصیف پرامپت',
    createChars: 'کاراکتر',
    createPromptPlaceholder: 'سوژه‌ها، نورپردازی، زاویه دید هنری، حال و هوای رنگی و عمق میدان را با جزئیات بنویسید...',
    createInspirationPresets: 'پیش‌فرض‌های الهام‌بخش:',
    createNegativePromptOptional: 'پرامپت منفی (اختیاری)',
    createNegativePromptDesc: 'عناصری که باید حذف شوند',
    createNegativePlaceholder: 'تار، آناتومی دفرمه، واترمارک، متن، خارج از کادر، کیفیت پایین...',
    createGenerationParams: 'پارامترهای تولید',
    createAspectRatio: 'نسبت ابعاد',
    createSquare: '۱:۱ (مربع)',
    createLandscape: '۱۶:۹ (افقی)',
    createStory: '۹:۱۶ (استوری/ریلز)',
    createEditorial: '۴:۳ (تحریریه)',
    createPortrait: '۳:۴ (عمودی)',
    createTargetResolution: 'کیفیت هدف',
    createStandard: 'استاندارد (۱۰۲۴x۱۰۲۴)',
    createHigh2K: 'بالا ۲K (بزرگ‌نمایی شده)',
    createUltra4K: 'فوق‌العاده ۴K (فقط الیت)',
    createAestheticStyle: 'سبک بصری',
    createPhotorealistic: 'واقع‌گرایانه',
    createCinematic: 'سینمایی',
    createDigitalArt: 'هنر دیجیتال',
    createAnime: 'انیمه',
    create3DIso: 'ایزومتریک ۳بعدی',
    createMinimalistVector: 'وکتور مینیمال',
    createSynthesizing: 'تولید دارایی با کیفیت بالا',
    createGeneratingVia: 'تولید تENSOR‌های انتشاری با جمینای فلش...',
    createOutputCanvas: 'بوم خروجی',
    createInspectFullscreen: 'نمایش تمام‌صفحه',
    createAspectLabel: 'نسبت ابعاد:',
    createResolutionLabel: 'کیفیت:',
    createFileSize: 'حجم فایل:',
    createCanvasReady: 'بوم آماده است',
    createCanvasDesc: 'پرامپت و پارامترها را در سمت چپ تنظیم کنید، سپس دکمه تولید را بزنید.',
    createHistory: 'تاریخچه',
    createPreviewTitle: 'پیش‌نمایش اثر تولید شده',
    createPromptLabel: 'پرامپت:',
    createClose: 'بستن',
    createDownload: 'دانلود',
    createGenerationFailed: 'تولید ناموفق',
    createCreditsRefunded: 'هر اعتبار کسر شده به طور خودکار بازپرداخت شده است.',
    createGenerateMedia: 'تولید رسانه',
    createCredit: 'اعتبار',
    createCredits: 'اعتبار',
    createInvalidImageFile: 'لطفاً یک فایل تصویری معتبر (PNG، JPG، WebP) آپلود کنید.',
    createImageTooLarge: 'حجم تصویر نباید بیشتر از ۱۵ مگابایت باشد.',
    createPromptRequired: 'لطفاً پرامپتی برای توصیف تصویر مورد نظرتان بنویسید.',
    createSourceImageRequired: 'لطفاً یک تصویر مرجع بارگذاری نمایید.',
    createInsufficientCredits: 'اعتبار شما کافی نیست. لطفاً پلن خود را ارتقا دهید.',

    // ==================== CHAT VIEW ====================
    chatHeaderTitle: 'دستیار هوش مصنوعی فرست‌مایند',
    chatHeaderDesc: 'مشاور خلاقیت، زیبایی‌شناسی و ایده‌پردازی مفاهیم بصری',
    chatDevTestMode: 'حالت تست توسعه',
    chatRegenerate: 'تولید مجدد',
    chatClear: 'پاک کردن',
    chatImageStudio: 'استودیو تصویر',
    chatEmptyTitle: 'کشف ایده‌های خلاقانه و نگارش پرامپت',
    chatEmptyDesc: 'درباره سبک‌های نورپردازی، پارامترهای لنز، ترکیب‌بندی، پالت‌های رنگی یا ژانرهای هنری سوال بپرسید.',
    chatEnterToSend: 'Enter برای ارسال',
    chatSend: 'ارسال',
    chatCopied: 'کپی شد',
    chatCopy: 'کپی',
    chatCreateImageFromPrompt: 'ایجاد تصویر از این پرامپت',
    chatTransferPrompt: 'انتقال پرامپت به استودیو تصویر',
    chatThinking: 'در حال فکر کردن با',
    chatGenerationInterrupted: 'تولید متوقف شد',
    chatDismiss: 'بستن',

    // ==================== FORGOT PASSWORD ====================
    forgotPasswordTitle: 'بازنشانی رمز عبور',
    forgotPasswordDesc: 'ایمیل خود را وارد کنید تا دستورالعمل بازیابی دریافت کنید',
    forgotPasswordSent: 'دستورالعمل بازیابی ارسال شد',
    forgotPasswordSentDesc: 'اگر حسابی با',
    forgotPasswordSentDesc2: 'وجود داشته باشد، لینک بازنشانی رمز عبور به ایمیل شما ارسال شده است.',
    forgotPasswordReturn: 'بازگشت به صفحه ورود',
    forgotPasswordSendReset: 'ارسال لینک بازنشانی',
    forgotPasswordBack: 'بازگشت به صفحه ورود',

    // ==================== LEGAL VIEWS ====================
    aboutBadge: 'معماری پلتفرم',
    aboutTitle: 'درباره فرست‌مایند',
    aboutDesc: 'فرست‌مایند به عنوان یک پلتفرم نرم‌افزاری خلاقانه سازمانی طراحی شده است که حول مدل‌های تولیدی با قابلیت اطمینان بالا ساخته شده. به جای کار به عنوان نمونه اولیه، زیرساخت ما ترازهای دقیق مصرف، تطبیق پرداخت تایید شده و جداسازی دقیق مستاجران را اجرا می‌کند.',
    aboutLedgerTitle: 'دفتر کل دقیق',
    aboutLedgerDesc: 'اعتبارها فقط زمانی کسر می‌شوند که کارها شروع به پردازش می‌کنند و در صورت تجربه تایم‌اوت یا خطا توسط مدل‌های خارجی، خودکار بازپرداخت می‌شوند.',
    aboutZeroLeakTitle: 'عدم نشت داده‌ها',
    aboutZeroLeakDesc: 'دارایی‌های کاربران دقیقاً به شناسه سازنده احراز هویت شده محدود شده‌اند.',
    contactBadge: 'پشتیبانی و استعلام‌ها',
    contactTitle: 'تماس با پشتیبانی',
    contactDesc: 'تیم مهندسی و مالی ما برای کمک به پلتفرم، ادغام‌های API و توافقات سازمانی در دسترس است.',
    contactEnterpriseTitle: 'بخش سازمانی و مالی',
    contactEmail: 'support@firstmind.ai',
    contactResponseTime: 'زمان پاسخ‌دهی SLA:',
    contactResponseTimeDesc: 'پشتیبانی استاندارد ظرف ۲۴ ساعت پاسخ می‌دهد. مشترکین پرو و الیت اولویت ۴ ساعته دارند.',
    contactSystemStatus: 'وضعیت سیستم:',
    contactSystemStatusDesc: 'تمام پایپ‌لاین‌های جمینای و ویو ۲۴/۷ نظارت می‌شوند.',
    termsTitle: 'شرایط استفاده',
    termsUpdated: 'آخرین به‌روزرسانی: سپتامبر ۲۰۲۶',
    terms1Title: 'پذیرش شرایط:',
    terms1Desc: 'با دسترسی یا استفاده از فرست‌مایند، شما موافقت می‌کنید که از نظر قانونی به این شرایط استفاده ملزم باشید.',
    terms2Title: 'حساب و امنیت:',
    terms2Desc: 'شما مسئول حفاظت از اعتبارنامه‌های ورود خود هستید.',
    terms3Title: 'مصرف تولید و اعتبار:',
    terms3Desc: 'اشتراک‌ها تخصیص ماهانه اعتبارات تولید را اعطا می‌کنند.',
    terms4Title: 'محتوای ممنوع:',
    terms4Desc: 'کاربران نمی‌توانند تصاویر افترا‌آمیز، آزاردهنده یا غیرقانونی تولید کنند.',
    privacyTitle: 'سیاست حریم خصوصی',
    privacyUpdated: 'آخرین به‌روزرسانی: سپتامبر ۲۰۲۶',
    privacy1Title: 'جمع‌آوری داده‌ها:',
    privacy1Desc: 'ما ایمیل، نام حساب، رمزهای عبور هش شده، شناسه‌های تراکنش، پرامپت‌های تولید و فایل‌های رسانه‌ای حاصل را فقط برای ارائه خدمات خلاقانه شما جمع‌آوری می‌کنیم.',
    privacy2Title: 'محرمانگی دارایی‌ها:',
    privacy2Desc: 'دارایی‌های بصری تولید شده به طور امن در ذخیره‌سازی جداگانه سرور ذخیره می‌شوند.',
    privacy3Title: 'بدون ردیابی ناخواسته:',
    privacy3Desc: 'ما داده‌های کاربران را به شبکه‌های تبلیغاتی نمی‌فروشیم.',
    refundTitle: 'سیاست بازپرداخت و اختلاف',
    refundUpdated: 'آخرین به‌روزرسانی: سپتامبر ۲۰۲۶',
    refund1Title: 'بازپرداخت خودکار اعتبار:',
    refund1Desc: 'اگر کار تولید هوش مصنوعی به دلیل قطعی مدل با وضعیت ناموفق خاتمه یابد، سیستم خودکار هزینه دقیق اعتبار را فوراً بازپرداخت می‌کند.',
    refund2Title: 'بازپرداخت اشتراک:',
    refund2Desc: 'درخواست‌های بازپرداخت هزینه اشتراک ظرف ۷ روز تقویمی از تاریخ شارژ واجد شرایط هستند.',

    // ==================== FOOTER ====================
    footerProduct: 'محصولات',
    footerTextToImage: 'متن به تصویر',
    footerImageToImage: 'تصویر به تصویر',
    footerTextToVideo: 'متن به ویدیو (ویو)',
    footerSubscriptionPlans: 'پلن‌های اشتراک',
    footerPlatform: 'پلتفرم',
    footerFeaturesOverview: 'نمای کلی قابلیت‌ها',
    footerAboutArchitecture: 'درباره معماری',
    footerContactSupport: 'تماس و پشتیبانی',
    footerReferralProgram: 'برنامه همکاری معرف ($۱)',
    footerLegal: 'قانونی',
    footerTermsOfService: 'شرایط استفاده',
    footerPrivacyPolicy: 'سیاست حریم خصوصی',
    footerRefundPolicy: 'سیاست بازپرداخت و اختلاف',
    footerCopyright: 'تمامی حقوق محفوظ است.',
    footerDataIsolation: 'جداسازی کامل داده‌ها و دفتر کل تراکنش‌ها',
    footerAiOnline: 'موتورهای هوش مصنوعی آنلاین',

    // ==================== SIDEBAR ====================
    sidebarSubscription: 'اشتراک',
    sidebarNoActivePlan: 'بدون پلن فعال',
    sidebarSelectPlan: 'انتخاب پلن',
    sidebarCredits: 'اعتبار',
    sidebarReferral: '۱ دلار/فروش',

    // ==================== تاریخچه تولیدات ====================
    historyTitle: 'آرشیو تاریخچه تولیدات',
    historyDesc: 'مخزن خصوصی و جداگانه تمام کارهای خلاقانه شما.',
    historyAllMedia: 'همه انواع رسانه',
    historyImagesOnly: 'فقط تصاویر',
    historyVideosOnly: 'فقط ویدیوها',
    historyAllStatuses: 'همه وضعیت‌ها',
    historyCompleted: 'تکمیل شده',
    historyProcessing: 'در حال پردازش',
    historyFailed: 'ناموفق',
    historyLoading: 'در حال بارگذاری دارایی‌های خلاقانه...',
    historyEmptyTitle: 'هنوز تولیدی ندارید.',
    historyEmptyDesc: 'اولین اثر هنری دیجیتال یا ویدیوی خود را با موتورهای خلاقانه ما بسازید.',
    historyLaunchStudio: 'راه‌اندازی استودیو متن به تصویر',
    historyInspect: 'بررسی',
    historyGet: 'دریافت',
    historySynthesizedAsset: 'دارایی تولید شده',
    historyCost: 'هزینه',
    historyRetry: 'تلاش مجدد',
    historyDeleteAsset: 'حذف دارایی',
    historyConfirmDelete: 'آیا مطمئنید که می‌خواهید این دارایی را از آرشیو خود حذف کنید؟',
    historyRetryFailed: 'تلاش مجدد برای تولید ناموفق بود.',
    historyDeleteFailed: 'حذف تولید ناموفق بود.',
    historyModalTitle: 'جزئیات آرشیو تولید',
    historyPrompt: 'پرامپت:',
    historyNegative: 'منفی:',
    historyTool: 'ابزار:',
    historyRatio: 'نسبت:',
    historyResolution: 'رزولوشن:',
    historyCreated: 'ایجاد شده:',
    historyDelete: 'حذف',
    historyClose: 'بستن',
    historyDownloadOriginal: 'دانلود اصل',

    // ==================== مالی و اشتراک ====================
    billingTitle: 'مدیریت صورتحساب و اشتراک',
    billingDesc: 'سهمیه‌های استفادی لحظه‌ای، پرداخت چند درگاهی و حسابداری فاکتور تایید شده.',
    billingRefresh: 'بروزرسانی دفتر',
    billingCurrentPlan: 'پلن فعلی',
    billingFreeTier: 'پلن رایگان',
    billingNoSubscription: 'اشتراک فعالی وجود ندارد',
    billingRenewsOn: 'چرخه فعلی در تاریخ تمدید می‌شود',
    billingSubscribePrompt: 'برای شروع تولید رسانه، یک پلن فعال تهیه کنید.',
    billingCreditsRemaining: 'اعتبار باقیمانده:',
    billingUsed: 'استفاده شده',
    billingAvailable: 'قابل دسترس',
    billingCancelAutoRenew: 'لغو تمدید خودکار اشتراک',
    billingCancelConfirm: 'آیا مطمئنید که می‌خواهید تمدید خودکار را لغو کنید؟ تا پایان دوره صورتحساب به دسترسی خود ادامه خواهید داد.',
    billingCancelFailed: 'لغو ناموفق بود.',
    billingActivePlan: 'پلن فعال',
    billingPerMonth: '/ ماه',
    billingMonthlyCredits: 'اعتبار ماهانه',
    billingCurrentTier: 'پلن فعلی',
    billingSelectPlanCheckout: 'انتخاب پلن و پرداخت',
    billingPaymentTitle: 'تراکنش‌های پرداخت و فاکتور مالیاتی',
    billingTransactionId: 'شناسه تراکنش',
    billingPlan: 'پلن',
    billingAmount: 'مبلغ',
    billingProvider: 'ارائه‌دهنده',
    billingStatus: 'وضعیت',
    billingDate: 'تاریخ',
    billingInvoice: 'فاکتور',
    billingPlanSubscription: 'اشتراک پلن',
    billingViewInvoice: 'مشاهده فاکتور',
    billingEmptyTitle: 'هنوز تاریخچه پرداختی ندارید.',
    billingEmptyDesc: 'فاکتورها، رسیدها و تراکنش‌های اشتراک تایید شده شما در اینجا نمایش داده می‌شوند.',
    billingCheckoutTitle: 'فعال‌سازی',
    billingCheckoutDesc: 'درگاه پرداخت مورد نظر خود را برای شروع تراکنش انتخاب کنید',
    billingMonthlyAutoRenew: 'تمدید خودکار ماهانه',
    billingPaymentProvider: 'ارائه‌دهنده پرداخت',
    billingProceedToPayment: 'رفتن به درگاه پرداخت',
    billingPaymentFailed: 'شروع پرداخت ناموفق بود.',
    billingTransactionRef: 'مرجع تراکنش:',
    billingAmountDue: 'مبلغ قابل پرداخت:',
    billingGateway: 'درگاه:',
    billingSimulating: 'شبیه‌سازی دست‌اند خودکار درگاه امن',
    billingSimulatingDesc: 'در محیط واقعی، کاربر ورود کارت یا انتقال رمزارز را از طریق صفحه ا redirection سازگار با PCI ارائه‌دهنده تکمیل می‌کند.',
    billingCancel: 'لغو',
    billingConfirmVerify: 'تایید و تایید پرداخت',
    billingVerifyFailed: 'تایید پرداخت ناموفق بود.',
    billingPaymentSuccess: 'پرداخت با موفقیت تایید شد!',
    billingQuotaAvailable: 'سهمیه',
    billingCreditsNowAvailable: 'اعتبار اکنون در استودیوی شما در دسترس است.',
    billingStartCreating: 'شروع به تولید دارایی',
    billingTaxInvoice: 'فاکتور مالیاتی و رسید',
    billingFirstMind: 'شرکت فناوری SaaS فست‌مایند',
    billingInvoiceNumber: 'فاکتور شماره',
    billingPaid: 'پرداخت شده',
    billingBilledTo: 'صورتحساب به نام:',
    billingIssueDate: 'تاریخ صدور:',
    billingDescription: 'توضیحات',
    billingStudioSubscription: 'پلن اشتراک استودیو',
    billingTotalPaid: 'کل پرداخت شده:',
    billingReceiptNote: 'رسید الکترونیکی تایید شده توسط دفتر تراکنش فست‌مایند تولید شده.',
    billingPrintSave: 'چاپ / ذخیره PDF',

    // ==================== سیستم معرف ====================
    referralsTitle: 'داشبورد شریک معرف',
    referralsBadge: '۱.۰۰ دلار / فروش واجد شرایط',
    referralsRule: 'قانون ۲۸: کمیسیون تکراری ۱.۰۰ دلاری تایید شده را در هر اشتراک معرف واجد شرایط در دفتر خود دریافت کنید.',
    referralsYourLink: 'لینک معرف منحصر به فرد شما',
    referralsInviteTitle: 'دیگر خالقان را دعوت کنید و کمیسیون خودکار کسب کنید',
    referralsInviteDesc: 'وقتی یک خالق با لینک یا کد شما ثبت‌نام کند و هر پلن پولی (Starter, Pro, Elite) را فعال کند، ۱.۰۰ دلار فوراً در دفتر شما ثبت می‌شود.',
    referralsLoadingLink: 'در حال بارگذاری لینک...',
    referralsCopied: 'کپی شد!',
    referralsCopyLink: 'کپی لینک',
    referralsTotalEarnings: 'کل درآمد تایید شده',
    referralsLifetimeSales: 'فروش‌های مادام‌العمر',
    referralsMonthlyEarnings: 'درآمد این ماه',
    referralsCurrentMonth: 'ماه جاری',
    referralsSubscribed: 'معرف‌های مشترک شده',
    referralsActiveCustomers: 'مشتریان فعال پولی',
    referralsLeaderboardRank: 'رتبه جهانی جدول امتیازات',
    referralsUnranked: 'بدون رتبه',
    referralsBasedOnCommissions: 'بر اساس کمیسیون‌های واقعی معرفی',
    referralsReferredAccounts: 'حساب‌های معرفی شده',
    referralsRecords: 'رکورد',
    referralsEmptyTitle: 'هنوز معرفی ندارید.',
    referralsEmptyDesc: 'لینک معرفی خود را به اشتراک بگذارید تا در هر مشترک واجد شرایط کمیسیون تکراری ۱.۰۰ دلاری کسب کنید.',
    referralsCopyAction: 'کپی لینک معرفی',
    referralsCreator: 'خالق',
    referralsStatus: 'وضعیت',
    referralsCommission: 'کمیسیون',
    referralsRegistered: 'تاریخ ثبت‌نام',
    referralsPaidCommissioned: 'پرداخت شده / کمیسیون دریافت شده',
    referralsRegisteredNoPlan: 'ثبت‌نام شده (بدون پلن)',
    referralsLeaderboard: 'جدول امتیازات معرفی',
    referralsGlobal: 'جهانی',
    referralsMonthly: 'ماهانه',
    referralsLeaderboardEmptyTitle: 'هنوز رکوردی در جدول امتیازات وجود ندارد.',
    referralsLeaderboardEmptyDesc: 'رتبه‌بندی‌ها با تکمیل کمیسیون‌های معرفی تایید شده نمایش داده می‌شوند.',
    referralsSales: 'فروش',

    // ==================== تنظیمات حساب ====================
    profileTitle: 'تنظیمات حساب و امنیت',
    profileDesc: 'پروفایل شخصی، اعتبارنامه‌ها و تنظیمات زبان خود را مدیریت کنید.',
    profilePersonalInfo: 'اطلاعات شخصی',
    profileUpdatedSuccess: 'تنظیمات پروفایل با موفقیت بروزرسانی شد.',
    profileEmailLabel: 'آدرس ایمیل',
    profileEmailNote: 'ایمیل‌های حساب قابل تغییر مستقیم نیستند.',
    profileFullName: 'نام کامل',
    profileTimezone: 'منطقه زمانی',
    profileLanguage: 'زبان ترجیحی',
    profileSavePreferences: 'ذخیره تنظیمات',
    profileSecurityPassword: 'امنیت و رمز عبور',
    profilePasswordSuccess: 'رمز عبور با موفقیت بروزرسانی شد.',
    profileCurrentPassword: 'رمز عبور فعلی',
    profileNewPassword: 'رمز عبور جدید (حداقل ۸ کاراکتر)',
    profileConfirmPassword: 'تایید رمز عبور جدید',
    profileUpdatePassword: 'بروزرسانی رمز عبور',
    profileSecurityTitle: 'اعتبارنامه‌های امنیتی و جداسازی',
    profileAuthScheme: 'روش احراز هویت:',
    profileAuthValue: 'PBKDF2 SHA-512 (۱۰,۰۰۰ تکرار)',
    profileTenantIsolation: 'جداسازی مستاجر:',
    profileTenantValue: 'ذخیره‌سازی با دامنه UID دقیق',
    profileAccountCreated: 'تاریخ ایجاد حساب:',

    // ==================== اعلان‌ها ====================
    notificationsTitle: 'فید اعلان‌ها',
    notificationsNew: 'جدید',
    notificationsDesc: 'بروزرسانی‌های لحظه‌ای درباره کارهای تولید، معرفی‌ها و فعالیت اشتراک.',
    notificationsMarkAllRead: 'خواندن همه',
    notificationsLoading: 'در حال بارگذاری اعلان‌ها...',
    notificationsEmptyTitle: 'اعلانی ندارید.',
    notificationsEmptyDesc: 'بروزرسانی‌های لحظه‌ای درباره کارهای تولید و صورتحساب در اینجا ثبت می‌شوند.',
    notificationsMarkRead: 'خواندن',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');
  const [currency, setCurrencyState] = useState<Currency>('USD');

  useEffect(() => {
    const savedLang = localStorage.getItem('firstmind_lang') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'fa')) {
      setLanguageState(savedLang);
    }
    const savedCurr = localStorage.getItem('firstmind_curr') as Currency;
    if (savedCurr && (savedCurr === 'USD' || savedCurr === 'IRR' || savedCurr === 'EUR')) {
      setCurrencyState(savedCurr);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('firstmind_lang', lang);
  };

  const setCurrency = (curr: Currency) => {
    setCurrencyState(curr);
    localStorage.setItem('firstmind_curr', curr);
  };

  const direction = language === 'fa' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.dir = direction;
    document.documentElement.lang = language;
  }, [direction, language]);

  const t = (key: string, defaultText?: string): string => {
    return translations[language]?.[key] || defaultText || key;
  };

  const formatPrice = (amountInUsd: number): string => {
    if (currency === 'IRR') {
      const irr = Math.round(amountInUsd * 600000);
      return `${irr.toLocaleString()} ریال`;
    } else if (currency === 'EUR') {
      const eur = (amountInUsd * 0.92).toFixed(2);
      return `€${eur}`;
    }
    return `$${amountInUsd.toFixed(2)}`;
  };

  const formatDate = (dateString: string): string => {
    try {
      const d = new Date(dateString);
      if (language === 'fa') {
        return new Intl.DateTimeFormat('fa-IR', {
          year: 'numeric',
          month: 'short',
          day: 'numeric',
          hour: '2-digit',
          minute: '2-digit'
        }).format(d);
      }
      return new Intl.DateTimeFormat('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      }).format(d);
    } catch {
      return dateString;
    }
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        direction,
        currency,
        setLanguage,
        setCurrency,
        t,
        formatPrice,
        formatDate
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
